language: python
python:
  - 3.7
services:
  - postgresql
script:
  - DATABASE_URL="postgresql://postgres@localhost" poetry run pytest --cov=streetwise --cov-report=xml
install:
  - pip install --upgrade pip
  - pip install poetry codecov
  - poetry install
  - FLASK_APP=streetwise DATABASE_URL="postgresql://postgres@localhost" flask db upgrade
after_success:
  - codecov
cache: pip yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn build
