"""empty message

Revision ID: 783f9ce1efe6
Revises: f1a6a55c8bb7
Create Date: 2020-06-16 21:58:25.639534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783f9ce1efe6'
down_revision = 'f1a6a55c8bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('shown', sa.Boolean(), nullable=True))
    op.execute('UPDATE images SET shown=TRUE')
    op.execute('UPDATE campaign SET name=\'safety\' WHERE id=1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'shown')
    # ### end Alembic commands ###
