"""empty message

Revision ID: 46ba6c8d1266
Revises: 
Create Date: 2020-05-07 00:15:26.268664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ba6c8d1266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('canton', sa.String(length=10), nullable=True),
    sa.Column('camera_angle', sa.Float(), nullable=True),
    sa.Column('sequence_key', sa.String(length=100), nullable=True),
    sa.Column('is_panorama', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(length=33), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('agent_address', sa.String(length=32), nullable=True),
    sa.Column('agent_platform', sa.String(length=64), nullable=True),
    sa.Column('agent_browser', sa.String(length=64), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('agent_string', sa.String(length=256), nullable=True),
    sa.Column('agent_width', sa.Integer(), nullable=True),
    sa.Column('agent_height', sa.Integer(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('other_id', sa.Integer(), nullable=True),
    sa.Column('is_leftimage', sa.Boolean(), nullable=True),
    sa.Column('is_undecided', sa.Boolean(), nullable=True),
    sa.Column('time_elapsed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choice_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['other_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('comments')
    op.drop_table('sessions')
    op.drop_table('images')
    op.drop_table('campaign')
    # ### end Alembic commands ###
